trigger:
  batch: true
  branches:
    include: 
    - '*'
  paths:
    include: 
    - nodebrady/
    - common/ci-steps-template.yml
    - common/cd-steps-template.yml
    
pr: none

pool:
  vmImage: ubuntu-latest

variables:
- template: ../common/ci-vars-template.yml
  parameters:
      projectName: nodebrady
  # define 3 more variables: registryName, registryLogin and registryPassword in the Azure pipeline UI definition

steps:
- template: ../common/ci-steps-template.yml


resources: 
  pipelines:
  - pipeline: ci-pipeline
    source: nodebrady-ci
    trigger:
      enabled: true
      branches:
        include:
          - master

stages:
- stage: development
  displayName: development
  jobs:
  - deployment: development
    variables:
      k8sNamespace: $(k8sNamespace)
      # define 5 more variables: aks, rg, aksSpId, aksSpSecret and aksSpTenantId in the Azure pipeline UI definition
    displayName: deploy helm chart into AKS
    pool:
      vmImage: ubuntu-latest
    environment: development-$(projectName)
    strategy:
      runOnce:
        deploy:
          steps:
          - template: ../common/cd-steps-template.yml
